---
- hosts: localhost
  gather_facts: false

  tasks:
  - name: Gather guest facts from vCenter
    vmware_guest_facts:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username}}'
      password: '{{ vcenter_password }}'
      validate_certs: '{{ validate_certs }}'
      name: Jumper
      datacenter: Datacenter
    register: facts

  - name: Display results
    debug:
      var: facts
