ansible_connection: network_cli
ansible_network_os: ios
admin_user: admin
domain_name: cisco.com
gateway_of_last_resort: 100.100.100.100
ntp_servers:
  - 10.10.10.10
  - 11.11.11.11
logging_source_interface: loopback0
logging_host: 20.20.20.20
snmp:
  - community: cisco
    privilege: ro
  - community: cisco_rw
    privilege: rw
radius_hosts:
  - 20.20.20.20
  - 21.21.21.21
