---
- hosts: ios_routers
  gather_facts: false

  tasks:
  - name: Generate Configuration Files
    template:
      src: ../templates/router_initial_configuration.j2
      dest: 'Generated Configurations/{{ hostname }}.txt'
